# For more information: https://laravel.com/docs/sail
version: "3"
services:
  portfolio-site:
    build:
      context: ./vendor/laravel/sail/runtimes/8.0
      dockerfile: Dockerfile
      args:
        WWWGROUP: "${WWWGROUP}"
    image: sail-8.0/app
    ports:
      - "${APP_PORT:-80}:80"
    environment:
      WWWUSER: "${WWWUSER}"
      LARAVEL_SAIL: 1
    volumes:
      - ".:/var/www/html"
    networks:
      - sail
  node:
    image: node
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    command: npm run watch-poll
    ports:
      - 3000:3000
      - 3001:3001
    depends_on:
      - portfolio-site
    networks:
      - sail

networks:
  sail:
    driver: bridge
